### ISSUE TITLE
MacPro6,1

### ISSUE THREAD

**Issue by IrvingGuerra** [mavethee/Hackintosh-OpenCore-EFI-HP-Z420#2]
Everything was going well, the USB started fine, I formatted the disk, but when trying to install Ventura the message appears.

Your Mac is not compatible with this version or something like that

can you help me? Im using MacPro6,1 in the config.plist

**Comment by mavethee** [comment]
Just regenerate to MacPro7,1 for the install process, MacPro6,1 is just cosmetic stuff and matches hardware more.
Then after install give it MacPro6,1 as USB mapping was made for MP6,1, you can do your own ofc.

It boots and runs fine but any fresh install need supported SMBIOSes.
