### ISSUE TITLE
Issue MacPro6,1 and 6,1

### ISSUE THREAD

**Issue by IrvingGuerra** [mavethee/Hackintosh-OpenCore-EFI-HP-Z420#3]
Hello, I want to report this issue.

When using MacPro6,1 if it enters the installer, but it says that the mac is not supported.

But when I switch to MacPro7,1, it doesn't even enter the installer. Crashes after selecting USB in OpenCore.

![IMG_20230122_165933](https://user-images.githubusercontent.com/37481550/213945240-877a23e8-2e9a-4758-8756-72ee4ba91cb9.jpeg)

**Comment by mavethee** [comment]
Not an issue, I mentioned you need to map your USBs.

Same model =/= Same hardware

My USBMap may not work for you.

OR just

Don't plug your USB into internal USB3 port.

README exists, people, just saying.
