### ISSUE TITLE
Audio only via internal speaker

### ISSUE THREAD

**Issue by ginodecock** [mavethee/Hackintosh-OpenCore-EFI-HP-Z420#6]
Hi,

The install of Ventura worked OK. Only except I only get audio via the internal speakers. Is there a setting to fix this?

**Comment by mavethee** [comment]
Well check if you have same audio codec (ALC262) and just switch layout, if it's somehow different, just look for yours.

https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

(CTRL/CMD + F -> search up your codec)

In both MacPro7,1 and MacPro6,1, you have different layouts assigned.

`config.plist` -> `NVRAM` -> `Add` -> `7C436110-AB2A-4BBB-A880-FE41995C9F82` -> `boot-args` -> `alcid=xxx` where `XXX` is your layout-id, e.g. `66`.
